### ISSUE TITLE
Annotation package not working for Java9

### ISSUE THREAD

**Issue by mpfritz** [nasa/trick#494] opened 2017-10-23 20:34 UTC
When attempting to compile Trick using Java9, I get the following errors involving the annotation package: 

 - (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
src/trick/common/utils/vs/Variable.java:11: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlElementRef;

 - (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
src/trick/common/utils/vs/VSValue.java:3: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlElement;

 - (package javax.xml.bind.annotation is declared in module java.xml.bind, which is not in the module graph)
src/trick/common/utils/vs/VSValue.java:4: error: package javax.xml.bind.annotation is not visible
import javax.xml.bind.annotation.XmlRootElement;

I can successfully compile if I disable the JAVA compilation. Any ideas to correct fix for this one?

**Comment by mpfritz** [comment] 2017-10-23 20:35
Adding @iamthad

**Comment by iamthad** [comment] 2017-10-23 21:03
Is this related / a dupe of #490?

**Comment by jmpenn** [comment] 2017-10-23 21:08
I believe it is.

**Comment by iamthad** [comment] 2017-11-07 15:40
This exact issue is described with a fix here: https://blog.codefx.org/java/java-9-migration-guide/#Dependencies-On-Java-EE-Modules

**Closed** 2018-03-05 19:35 UTC
