### ISSUE TITLE
Add option to terminate a sim on a Python error in Trick events

### ISSUE THREAD

**Issue by jdeans289** [nasa/trick#1433] opened 2023-01-19 21:02 UTC
The input processor is used to run Trick events or add_read statements that take place at any time during a sim's execution, but unlike the initial input file processing, any errors raised by the Python code will not affect the running sim. This can result in silent python failures, especially in CI pipelines. Add an option to terminate the sim if a Python error is detected at any point during the run.

This issue can be closed when:
1. The above feature is implemented, tested, and documented.

**Comment by iamthad** [comment] 2023-01-20 16:50
Dupe of #693

**Closed** 2023-01-20 21:46 UTC
